### ISSUE TITLE
cyd_saldept vs cyd_salprofs

### ISSUE THREAD

**Issue by jarad** [lydiaPenglish/CyChecks2#1]
The distinction between these two data sets is unclear to me and the help files aren't helping.

**Comment by lydiaPenglish** [comment]
Both data-sets are filtered to have only people with "prof" somewhere in their title. `cyd_salprofs` is a subset of `cyd_saldept` in that it doesn't have the "weird" professor titles (chair, emeritus, collaborating, visiting, etc). and it also lumps together distinguished, university, and morrill professors into an "awarded" category. 

If it's redundant to have both data-sets then I might suggest we have a function to "simplify" the professor titles. How does that sound? @vanichols

**Comment by jarad** [comment]
I like this suggestion.

**Comment by vanichols** [comment]
Yes that is a good idea. 
I don't get notifications about issues on this repo...I will try to figure that out. 
There is a dumb thing with gender fractions in each department - I'll delete that, it was me trying to figure out why something in Shiny wasn't working.

**Comment by lydiaPenglish** [comment]
I've update this function so it should work with the `salaries` (or any joined) data. We can delete `cyd_saldept` eventually, see issue #10
