### ISSUE TITLE
New department data set

### ISSUE THREAD

**Issue by jarad** [lydiaPenglish/CyChecks2#3]
I suggest we create a new data set that provides the abbreviated `dept`, the full department name, the 3-4 letter code for each department, and the college the department is in. 

We could then also remove `college` from the salary data.frame as we can just join this data frame with that one later.

**Comment by lydiaPenglish** [comment]
Sounds good. Something to consider: some departments have changed names over time. Could we have another column that has "former name" or "alternate name" to keep track of those changes? I'm trying to think of a better way than just doing this: 

`dplyr::mutate(dept = dplyr::recode(dept, 
                                     "anthro old"      = "anthropology",
                                     "curr/instr"      = "school of ed",
                                     "ed ldshp pol st" = "school of ed"))`

**Comment by jarad** [comment]
[Here](https://www.ir.iastate.edu/deptcodes) is an Excel file containing the department information.

**Comment by jarad** [comment]
I think we don't worry too much about special cases. Let's a basic analysis done such that we can rerun it whenever and we'll deal with special cases as we can/want to.
