### ISSUE TITLE
Why the cyf_ and cyd_ prefixes?

### ISSUE THREAD

**Issue by jarad** [lydiaPenglish/CyChecks2#7]
I'm curious why you decided to put cyf_ prefixes on functions and cyd_ prefixes on data. This just seems like extra type. If there was a concern over possible confusion with other functions or data, you can always use CyChecks2::<function> or CyChecks2::<data>.

**Comment by lydiaPenglish** [comment]
I'm happy to delete those prefixes, but I'll let @vanichols have the final say.

**Comment by vanichols** [comment]
It is extra typing, but for me I don't always remember what we called the data (ex was it saldept or deptsals??), so when I type cyd_ it fills in possibilities for me to choose from. Same logic for the functions.

**Comment by jarad** [comment]
Ah. I didn't think about autocomplete.
