### ISSUE TITLE
snapshot data with middle names

### ISSUE THREAD

**Issue by jarad** [lydiaPenglish/CyChecks2#9]
I see you have done a [lot of work](https://github.com/lydiaPenglish/CyChecks2/blob/master/data-raw/_raw/duplicate_reconcilation_process.txt) to deal with duplicate first and last names and have [dealt with some of them](https://github.com/lydiaPenglish/CyChecks2/blob/master/data-raw/_raw/duplicate_name_reconciliation.csv). I was wondering if we could request a new version of the snapshot data that includes middle names. It seems this would go a long way toward fixing the duplicate name issue.

**Comment by vanichols** [comment]
I'll email HR and ask for a Jan 2019 snapshot with middle names. I'll cc both of you. 

Jarad watching your thought process is very helpful!

**Comment by jarad** [comment]
Added in dba5b4f1ecf696cb9ca53b82b89c28123cc4fe44
